### ISSUE TITLE
Im getting error when importing the module, please help.

### ISSUE THREAD

**Issue by moderalsamarrai** [cck020025/odoo-apps#1]
Hello and thank you for the module
im facing an error when trying to import the module to my odoo online demo, and to my offline installtion.

when clicking on "import module" in the setting app, i get the following error:

```
Error while importing module 'cck_sn_to_eq'.

 while parsing /tmp/tmpla8t1c30/cck_sn_to_eq/views/stock_lot.xml:3
Error while validating view near:

<form string="Lots/Serial Numbers">
                <sheet>
                <field name="company_id" invisible="1"/>
                <field name="display_complete" invisible="1"/>
                <field name="product_tracking" invisible="1" __validate__="1"/>

Field "product_tracking" does not exist in model "stock.lot"

View error context:
{'file': '/tmp/tmpla8t1c30/cck_sn_to_eq/views/stock_lot.xml',
 'line': 3,
 'name': 'stock.lot.form.eq',
 'view': ir.ui.view(3229,),
 'view.model': 'stock.lot',
 'view.parent': ir.ui.view(1669,),
 'xmlid': 'stock_lot_form_eq'}
 
 Make sure those modules are installed and try again.
```

I have installed the maintenance, inventory, and mail module.

thank you in advance

**Comment by cck020025** [comment]
Sorry for the late reply.
I am afraid the "Base Import Module" (base_import_module) does not support users to import a python code.
[https://github.com/odoo/odoo/blob/master/addons/base_import_module/__manifest__.py#L9-L10](https://github.com/odoo/odoo/blob/master/addons/base_import_module/__manifest__.py#L9-L10)
